name = "SimplicialSets"
uuid = "3f952873-5d0e-4cfa-8412-438bae177e42"
authors = ["matthias314"]
version = "0.2.0"

[deps]
StructEqualHash = "8bd03d06-bfef-4aaf-8250-1a26cbb401bf"
LinearCombinations = "67be3549-475c-46bf-8928-de3404d670d9"

[compat]
julia = "1.6"
StructEqualHash = "0.1"
LinearCombinations = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
